apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: thesis-demo-prod-in-cluster
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: thesis-demo-prod
  project: default
  source:
    path: kustomize/overlays/prod/
    repoURL: https://github.com/mattedamo/thesis-demo-infrastructure.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
