name: delete-manifest

on: 
  workflow_dispatch:
    inputs:
      code-branch:
        description: 'branch of code repository that has been deleted'
        required: true
      app-name:
        description: 'name of the app'
        required: true
      tier: 
        description: 'tier of the app'
        required: true


jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    
    steps:
      - name: set environment variables
        uses: allenevans/set-env@v2.0.0
        with:
          CODE_BRANCH:  ${{ github.event.inputs.code-branch}}
          APP_NAME: ${{ github.event.inputs.app-name }}
          TIER: ${{ github.event.inputs.tier }}

      - name: Check out code
        uses: actions/checkout@v2
    
      - name: Setup Python
        uses: actions/setup-python@v2
        with: 
          python-version: "3.x"
          
      - run: python scripts/delete-manifest.py
        name: Delete manifests
    
      - name: Add and commit changes
        uses: EndBug/add-and-commit@v6
        with:
          message: "deleted manifests"
           
